Set-Alias -Name lg -Value lazygit -Description "lazygit utility alias"
Set-Alias -Name cmg -Value Connect-MgGraphApi -Description "Custom MgGraph connect function"
Set-Alias -Name dmg -Value Disconnect-MgGraphApi -Description "Custom MgGraph disconnect function"
Set-Alias -Name cme -Value Connect-ExchOnline -Description "Custom ExchangeOnline connect function"
Set-Alias -Name dme -Value Disconnect-ExchOnline -Description "Custom ExchangeOnline disconnect function"
Set-Alias -Name caz -Value Connect-Azure -Description "Custom Az connect function"
Set-Alias -Name daz -Value Disconnect-Azure -Description "Custom Az disconnect function"
Set-Alias -Name cs -Value Connect-Server -Description "Custom Enter-PSSession function for servers"
Set-Alias -Name tm -Value procexp -Description "process explorer"
Set-Alias -Name ghidra -Value D:\ghidra_12.0_PUBLIC\ghidraRun.bat -Description "Ghidra app runner"
