local M = {
  require 'plugins.alpha',
  require 'plugins.autopairs',
  require 'plugins.conform',
  --  require 'plugins.copilot',
  require 'plugins.gitsigns',
  require 'plugins.lazydev',
  require 'plugins.lualine',
  require 'plugins.luv',
  require 'plugins.markdown',
  require 'plugins.mason',
  require 'plugins.mini',
  require 'plugins.nerdtree',
  require 'plugins.nuget',
  require 'plugins.nvim-ufo',
  require 'plugins.obsidian',
  require 'plugins.onedark',
  require 'plugins.powershell',
  require 'plugins.roslyn',
  require 'plugins.telescope',
  require 'plugins.todo-comments',
  require 'plugins.treesitter',
  require 'plugins.uv',
  require 'plugins.vim-dadbod',
  require 'plugins.whichkey',
  'tpope/vim-fugitive',
  'xiyaowong/transparent.nvim',
  'rafamadriz/friendly-snippets',
}
return M
